databases:
  - name: grace-friends
    databaseName: grace-friends_development
    user: admin

services:
  - type: web
    name: grace-friends
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grace-friends_development
          property: connectionString
      - key: 98d317b055e394daf523c34178bd0e27
        sync: false
